# Generated by Django 6.0.4 on 2026-04-22 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_ref', models.CharField(max_length=32, unique=True)),
                ('day_label', models.CharField(max_length=32)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField()),
                ('room_label', models.CharField(max_length=32)),
                ('teams_link', models.URLField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'ordering': ['start_at', 'room_label'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='scheduled', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interviewee', models.OneToOneField(limit_choices_to={'role': 'interviewee'}, on_delete=django.db.models.deletion.PROTECT, related_name='interview_as_interviewee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewPanelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.interview')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'interviewer'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='interview',
            name='panelists',
            field=models.ManyToManyField(related_name='interviews_as_panelist', through='interviews.InterviewPanelist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RescheduleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('forwarded', 'Forwarded'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=16)),
                ('external_ref', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_requests', to='interviews.interview')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reschedule_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='interview',
            name='timeslot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='interview', to='interviews.timeslot'),
        ),
        migrations.AddIndex(
            model_name='interviewpanelist',
            index=models.Index(fields=['user'], name='interviews__user_id_7b127f_idx'),
        ),
        migrations.AddConstraint(
            model_name='interviewpanelist',
            constraint=models.UniqueConstraint(fields=('interview', 'user'), name='unique_panelist_per_interview'),
        ),
    ]
