# Generated by Django 6.0.4 on 2026-05-22 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_timeslot_interview_interviewpanelist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='timeslot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interview', to='interviews.timeslot'),
        ),
    ]
