# Generated by Django 6.0.4 on 2026-05-24 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_alter_interview_timeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('opens_at', models.DateTimeField()),
                ('closes_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed')], default='draft', max_length=8)),
                ('min_available_slots', models.PositiveIntegerField(default=0, help_text='Panelists must mark at least this many timeslots available (0 = no minimum).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-opens_at'],
            },
        ),
        migrations.CreateModel(
            name='PanelistAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('available', 'Available'), ('preferred', 'Preferred'), ('unavailable', 'Unavailable')], default='available', max_length=12)),
                ('panelist', models.ForeignKey(limit_choices_to={'role': 'interviewer'}, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL)),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='interviews.timeslot')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='interviews.preferenceround')),
            ],
            options={
                'indexes': [models.Index(fields=['round', 'panelist'], name='interviews__round_i_a39eef_idx')],
                'constraints': [models.UniqueConstraint(fields=('round', 'panelist', 'timeslot'), name='unique_availability_per_slot')],
            },
        ),
    ]
