# Generated by Django 6.0.4 on 2026-05-26 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulePublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('published', 'Published'), ('discarded', 'Discarded')], default='proposed', max_length=10)),
                ('solver_status', models.CharField(blank=True, max_length=32)),
                ('objective_value', models.BigIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='interviews.preferenceround')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='interviews.schedulepublication'),
        ),
        migrations.CreateModel(
            name='ProposalAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.interview')),
                ('timeslot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interviews.timeslot')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='interviews.schedulepublication')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('publication', 'interview'), name='unique_assignment_per_publication')],
            },
        ),
    ]
